# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://www.stoloto.ru/")
    self.driver.set_window_size(1616, 876)
    self.driver.find_element(By.CSS_SELECTOR, ".links > .pseudo").click()
    self.driver.find_element(By.ID, "auth_login").click()
    self.driver.find_element(By.ID, "auth_login").send_keys("89154482623")
    self.driver.find_element(By.ID, "auth_password").click()
    self.driver.find_element(By.ID, "auth_password").send_keys("Test2018")
    self.driver.find_element(By.CSS_SELECTOR, ".submit_button_container > .pretty_button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg_7x49 .game_card_about ins").click()
    self.driver.execute_script("window.scrollTo(0,306)")
    self.driver.find_element(By.CSS_SELECTOR, ".quickies:nth-child(8) .fastfill-rnd").click()
    self.driver.find_element(By.NAME, "7x49_cart").click()
    element = self.driver.find_element(By.ID, "layout")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".medium a").click()
  
